# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         XML-XSPF
version:      0.5.1
version_from: lib/XML/XSPF.pm
installdirs:  site
requires:
    Class::Accessor:               0.20
    Date::Parse:                   2.20
    HTML::Entities:                1.30
    XML::Parser:                   2.30
    XML::Writer:                   0.600

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
